### PR TITLE
Export PYTHONPATH in env.sh

### PR DESCRIPTION
**Pull request by AlexanderFabisch**
Hi, I think we solved this problem before? Anyway, we must add this environment variable to be able to use the Python part of bolero.

### CODE REVIEW

**Comment by AlexanderFabisch** [comment]
OK, I think I solved the problem although I don't have access to any machine that does not have Python.

**Comment by AlexanderFabisch** [comment]
OK, now it should work ;)

**Comment by malter** [comment]
Great, I will check on a Windows system asap.
Can you use your fork in your bootstrap script until I checked the changes on OS X and Windows?

**Comment by AlexanderFabisch** [comment]
OK.

**Comment by AlexanderFabisch** [comment]
Did you check already @malter ?

**Pull request merged**
